/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ACER
 */
public class calculator extends javax.swing.JFrame {

    String angka;
    double total,angka1,angka2;
    int pilih;
    public calculator() {
        initComponents();
        angka="";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        display = new javax.swing.JTextField();
        tblHapus = new javax.swing.JButton();
        tblAngka7 = new javax.swing.JButton();
        tblPlusMin = new javax.swing.JButton();
        tblAngka3 = new javax.swing.JButton();
        tblKali = new javax.swing.JButton();
        tblKurang = new javax.swing.JButton();
        tblAngka9 = new javax.swing.JButton();
        tblAngka8 = new javax.swing.JButton();
        tblBagi = new javax.swing.JButton();
        tblAngka4 = new javax.swing.JButton();
        tblPersen = new javax.swing.JButton();
        tblAngka6 = new javax.swing.JButton();
        tblAngka5 = new javax.swing.JButton();
        tblTambah = new javax.swing.JButton();
        tblAngka1 = new javax.swing.JButton();
        tblAngka2 = new javax.swing.JButton();
        tblAngka0 = new javax.swing.JButton();
        tblKoma = new javax.swing.JButton();
        tblHasil = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayActionPerformed(evt);
            }
        });

        tblHapus.setText("c");
        tblHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblHapusActionPerformed(evt);
            }
        });

        tblAngka7.setText("7");
        tblAngka7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblAngka7ActionPerformed(evt);
            }
        });

        tblPlusMin.setText("+/-");
        tblPlusMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblPlusMinActionPerformed(evt);
            }
        });

        tblAngka3.setText("3");
        tblAngka3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblAngka3ActionPerformed(evt);
            }
        });

        tblKali.setText("*");
        tblKali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblKaliActionPerformed(evt);
            }
        });

        tblKurang.setText("-");
        tblKurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblKurangActionPerformed(evt);
            }
        });

        tblAngka9.setText("9");
        tblAngka9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblAngka9ActionPerformed(evt);
            }
        });

        tblAngka8.setText("8");
        tblAngka8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblAngka8ActionPerformed(evt);
            }
        });

        tblBagi.setText("/");
        tblBagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblBagiActionPerformed(evt);
            }
        });

        tblAngka4.setText("4");
        tblAngka4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblAngka4ActionPerformed(evt);
            }
        });

        tblPersen.setText("%");
        tblPersen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblPersenActionPerformed(evt);
            }
        });

        tblAngka6.setText("6");
        tblAngka6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblAngka6ActionPerformed(evt);
            }
        });

        tblAngka5.setText("5");
        tblAngka5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblAngka5ActionPerformed(evt);
            }
        });

        tblTambah.setText("+");
        tblTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblTambahActionPerformed(evt);
            }
        });

        tblAngka1.setText("1");
        tblAngka1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblAngka1ActionPerformed(evt);
            }
        });

        tblAngka2.setText("2");
        tblAngka2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblAngka2ActionPerformed(evt);
            }
        });

        tblAngka0.setText("0");
        tblAngka0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblAngka0ActionPerformed(evt);
            }
        });

        tblKoma.setText(",");
        tblKoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblKomaActionPerformed(evt);
            }
        });

        tblHasil.setText("=");
        tblHasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblHasilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(display)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(tblAngka7, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(tblAngka8, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(tblAngka9, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(tblKali, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createSequentialGroup()
                    .addComponent(tblHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(tblPlusMin, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(tblPersen, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(tblBagi, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(tblAngka0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tblKoma, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(tblAngka1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tblAngka2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tblAngka3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(tblAngka4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tblAngka5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tblAngka6, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tblKurang, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tblTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tblHasil, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(display, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tblHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tblPlusMin, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tblPersen, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tblBagi, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tblAngka7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tblAngka8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tblAngka9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tblKali, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tblAngka4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tblAngka5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tblAngka6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tblKurang, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tblAngka3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tblTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tblAngka1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tblAngka2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tblAngka0, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tblKoma, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tblHasil, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblAngka3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblAngka3ActionPerformed
        angka+="3";
        display.setText(angka);
    }//GEN-LAST:event_tblAngka3ActionPerformed

    private void displayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_displayActionPerformed

    private void tblHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblHapusActionPerformed
        display.setText("");
        angka1=0;
        angka2=0;
        total=0;
        angka="";
    }//GEN-LAST:event_tblHapusActionPerformed

    private void tblKomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblKomaActionPerformed
        angka+=".";
        display.setText(angka);
    }//GEN-LAST:event_tblKomaActionPerformed

    private void tblAngka0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblAngka0ActionPerformed
        angka+="0";
        display.setText(angka);
    }//GEN-LAST:event_tblAngka0ActionPerformed

    private void tblAngka1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblAngka1ActionPerformed
        angka+="1";
        display.setText(angka);
    }//GEN-LAST:event_tblAngka1ActionPerformed

    private void tblAngka2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblAngka2ActionPerformed
        angka+="2";
        display.setText(angka);
    }//GEN-LAST:event_tblAngka2ActionPerformed

    private void tblAngka4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblAngka4ActionPerformed
        angka+="4";
        display.setText(angka);
    }//GEN-LAST:event_tblAngka4ActionPerformed

    private void tblAngka5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblAngka5ActionPerformed
        angka+="5";
        display.setText(angka);
    }//GEN-LAST:event_tblAngka5ActionPerformed

    private void tblAngka6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblAngka6ActionPerformed
        angka+="6";
        display.setText(angka);
    }//GEN-LAST:event_tblAngka6ActionPerformed

    private void tblAngka7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblAngka7ActionPerformed
        angka+="7";
        display.setText(angka);
    }//GEN-LAST:event_tblAngka7ActionPerformed

    private void tblAngka8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblAngka8ActionPerformed
        angka+="8";
        display.setText(angka);
    }//GEN-LAST:event_tblAngka8ActionPerformed

    private void tblAngka9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblAngka9ActionPerformed
        angka+="9";
        display.setText(angka);
    }//GEN-LAST:event_tblAngka9ActionPerformed

    private void tblTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblTambahActionPerformed
        angka1=Double.parseDouble(angka);
        display.setText("+");
        angka="";
        pilih=1;
    }//GEN-LAST:event_tblTambahActionPerformed

    private void tblKurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblKurangActionPerformed
        angka1=Double.parseDouble(angka);
        display.setText("-");
        angka="";
        pilih=2;
    }//GEN-LAST:event_tblKurangActionPerformed

    private void tblKaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblKaliActionPerformed
        angka1=Double.parseDouble(angka);
        display.setText("*");
        angka="";
        pilih=3;
    }//GEN-LAST:event_tblKaliActionPerformed

    private void tblBagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblBagiActionPerformed
        angka1=Double.parseDouble(angka);
        display.setText("/");
        angka="";
        pilih=4;
    }//GEN-LAST:event_tblBagiActionPerformed

    private void tblPersenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblPersenActionPerformed
        angka2=Double.parseDouble(angka);
        total=angka2/100;
        angka=Double.toString(total);
        display.setText(angka);
    }//GEN-LAST:event_tblPersenActionPerformed

    private void tblPlusMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblPlusMinActionPerformed
        angka2=Double.parseDouble(angka);
        total=0-angka2/100;
        angka=Double.toString(total);
        display.setText(angka);
    }//GEN-LAST:event_tblPlusMinActionPerformed

    private void tblHasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblHasilActionPerformed
        switch(pilih){
            case 1:
                angka2=Double.parseDouble(angka);
                total=angka1+angka2;
                angka=Double.toString(total);
                display.setText(angka);
                break;
            case 2:
                angka2=Double.parseDouble(angka);
                total=angka1-angka2;
                angka=Double.toString(total);
                display.setText(angka);
                break;
            case 3:
                angka2=Double.parseDouble(angka);
                total=angka1*angka2;
                angka=Double.toString(total);
                display.setText(angka);
                break;
            case 4:
                angka2=Double.parseDouble(angka);
                total=angka1/angka2;
                angka=Double.toString(total);
                display.setText(angka);
                break;
        }
    }//GEN-LAST:event_tblHasilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField display;
    private javax.swing.JButton tblAngka0;
    private javax.swing.JButton tblAngka1;
    private javax.swing.JButton tblAngka2;
    private javax.swing.JButton tblAngka3;
    private javax.swing.JButton tblAngka4;
    private javax.swing.JButton tblAngka5;
    private javax.swing.JButton tblAngka6;
    private javax.swing.JButton tblAngka7;
    private javax.swing.JButton tblAngka8;
    private javax.swing.JButton tblAngka9;
    private javax.swing.JButton tblBagi;
    private javax.swing.JButton tblHapus;
    private javax.swing.JButton tblHasil;
    private javax.swing.JButton tblKali;
    private javax.swing.JButton tblKoma;
    private javax.swing.JButton tblKurang;
    private javax.swing.JButton tblPersen;
    private javax.swing.JButton tblPlusMin;
    private javax.swing.JButton tblTambah;
    // End of variables declaration//GEN-END:variables
}
